# Generated by Django 2.2.7 on 2019-11-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='recipient_account',
            new_name='receiver_account',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='recipient_name',
            new_name='receiver_name',
        ),
    ]
