# Generated by Django 2.2.7 on 2019-12-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transfer_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='confirmed',
        ),
    ]
