# Generated by Django 2.2.7 on 2019-12-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_remove_transfer_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
