# Generated by Django 2.2.7 on 2019-12-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_transfer_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='confirmed',
            new_name='confirm',
        ),
    ]
